warning text

diff --git a/.github/workflows/sig-sec-check.yml b/.github/workflows/sig-sec-check.yml
--- a/.github/workflows/sig-sec-check.yml
+++ b/.github/workflows/sig-sec-check.yml
@@ -36,7 +36,7 @@ jobs:
             do
               if [[ $file_name == *".md" ]] 
               then 
-                markdownlint $file_name || echo "Lints detected in $file_name"
+                markdownlint $file_name || echo "::warning Lints detected in $file_name"
               fi 
           done          
   Spelling:
@@ -51,7 +51,7 @@ jobs:
         run: | 
           npm install -g cspell
           git fetch origin master:master        
-          git diff --name-only master $HEAD | xargs -L1 echo "::warning $(npx cspell)" || echo "Spelling errors detected"
+          git diff --name-only master $HEAD | xargs -L1 npx cspell || echo "::warning Spelling errors detected"
   Links:
     runs-on: ubuntu-latest
     needs: Setup      
@@ -68,6 +68,6 @@ jobs:
             do
               if [[ $file_name == *".md" ]] 
               then 
-                npx markdown-link-check $file_name || echo "Bad links detected in $file_name"
+                npx markdown-link-check $file_name || echo "::warning Bad links detected in $file_name"
               fi 
           done
